### ISSUE TITLE
`expand` and `deleted` are boolean parameters in the `/source/<project>` GET command

### ISSUE THREAD

**Issue by boiko** [crazyscientist/osc-tiny#106]
If `deleted` is not handle as a boolean, when listing projects which have multibuild packages, all variants are returned as results, which is far from the intended behavior.

So deleted and expand should be treated as boolean parameters in the context of listing project packages.

**Comment by boiko** [comment]
> WTF? When was this changed?
Not sure if it was changed, but I tried out the use case that drove this whole discussion and it was still broken (listing packages of a project without including the possible multibuild variants) 

> All the work I did on osc-tiny was related to workarounds about query parameters. The API docs indicated that for this endpoint `deleted` and `expand` are no boolean params (in the sense of the OBS API, i.e. flags) but actual boolean params (represented by the values `0` and `1`).
> 
> It's even the very same endpoint that I complained about in [openSUSE/open-build-service#9715](https://github.com/openSUSE/open-build-service/issues/9715).

Yep, it is, that's how I spotted the problem.

**Comment by crazyscientist** [comment]
Ah, yes, this endpoint expected boolean _flags_ when I tested it over two months ago, too. But when I discovered that there are also parameters that expect boolean _values_, I only converted those to flags, which are explicitly declared as `bool` in the API docs.

Guess what: This particular API endpoint does not declare these params as `bool`. Mystery solved...

**Comment by crazyscientist** [comment]
Next attempt: https://github.com/openSUSE/open-build-service/issues/13215
