### ISSUE TITLE
`expand=True` is not a good default for the packages.get_list() method

### ISSUE THREAD

**Issue by boiko** [crazyscientist/osc-tiny#108]
The default expected behavior for listing packages of a project is always to only show packages that exist in the given project.

According to the API docs, when invoked with `expand`, the `GET /source/<project>` call lists all packages from the project plus all packages from linked projects, which is usually not the desired behavior for a default.

Even `osc` itself works this way when listing project packages.

It is worth mentioning that `expand=True` works as a good default for listing package contents though.

**Comment by crazyscientist** [comment]
Makes sense to me :slightly_smiling_face:
