### ISSUE TITLE
Due to an inconsistent behavior of the OBS API, multibuild variants are listed in the package results.

### ISSUE THREAD

**Issue by boiko** [crazyscientist/osc-tiny#72]
Due to a bug in the OBS API endpoint (reported here: https://github.com/openSUSE/open-build-service/issues/12925) when explicitly passing `deleted=0` in the `/sources/<proj>` endpoint, the multibuild versions of packages are listed in the results, see this example:

```
> osc api /source/devel:languages:python:Factory | grep python36
  <entry name="python36"/>
```

Now if I append `deleted=0`  to the arguments, the API endpoint lists also multibuild variants:
```
> osc api /source/devel:languages:python:Factory?deleted=0 | grep python36
  <entry name="python36"/>
  <entry name="python36:base" originpackage="python36"/>
  <entry name="python36:doc" originpackage="python36"/>
```

Until this gets fixed upstream, it would be nice if osc-tiny could omit the `deleted=0` from the API request.

**Comment by crazyscientist** [comment]
I had reported this already two years ago: https://github.com/openSUSE/open-build-service/issues/9715 :joy:

**Comment by crazyscientist** [comment]
Given the discussion in this original issue, I would not object to a work around in `osc-tiny`, but I'm afraid that there is a _method to the madness_ and it would be nice to have a single workaround to catch them all.
