### ISSUE TITLE
API docs don't get populated

### ISSUE THREAD

**Issue by der-gabe** [crazyscientist/osc-tiny#92]
The [API section](https://osc-tiny.readthedocs.io/en/latest/api.html) in the official `osc-tiny` docs on Read the Docs is basically empty.

Looking at the ReST file [api.rst](https://github.com/crazyscientist/osc-tiny/blob/master/doc/source/api.rst) that is supposed to generate that section, there are a bunch of `.. automodule::` directives in there, which should nomally create documentation sections for modules, functions, classes and methods and fill them in with the corresponding docstring.

Loos like that's not working.

**Comment by crazyscientist** [comment]
Thank you for noticing

**Comment by crazyscientist** [comment]
It seems, RTD builds the docs with Python3.7, which then fails accordingly:
```
WARNING: autodoc: failed to import module 'osc' from module 'osctiny'; the following exception was raised:
No module named 'cached_property'

**Comment by der-gabe** [comment]
So this needs to be fixed on the Read the Docs side of things, by adding a dependency?

**Comment by crazyscientist** [comment]
Or by adding a config file that tells RTD to use a more recent Python version... :grin:

**Comment by der-gabe** [comment]
That's great! Thanks!
